### ISSUE TITLE
localcolumn with out/multiple values id(s) error

### ISSUE THREAD

**Issue by srinivasseema** [RecordEvolution/TDMtermite#12]
Trying to read 17 MB tdx files throwing below error:
tdm_obj = tdm_termite.tdmtermite(bytes(tdmPath, encoding='utf-8'), bytes(tdxPath, encoding='utf-8'))

error message: localcolumn with out/multiple values id(s)

Is there any data size limitations in using TDMtermite ?

**Comment by mario-fink** [comment]
No, there's actually no intrinsic size limitation. The limit is only given by the relation of the tdx/tdm file sizes to the used hardware. 

The error message says that the relationship between some elements of the tdm/XML-tree seems to be ambiguous. Are you able to share your TDM (TDX) file(s) ?

**Comment by wagnejse** [comment]
@mario-fink Sorry, we can not share the concrete TDM/TDX files. Is there some way we could debug / investigate where the problem originates?

Thanks for your support 👍

**Comment by adamjnicholls** [comment]
Hi, @mario-fink I also have the same issue, with little explanation.
I'm afraid I also cannot share the problematic TDM & tdx files... and secondly, I don't have great control over the generation of the TDM/tdx file as they come from another piece of software.

Is there anything we should check on the TDM/tdx file

**Comment by mario-fink** [comment]
@wagnejse @adamjnicholls Do you have a machine at hand to build a development version of the package? This machine should have MSVC (win32) or gcc (Unix) and evtl. python3 with setuptools and cython installed. I will set up a dev branch for you to test some options to resolve the problem above. However, since I neither have access to the before mentioned TDM/TDX files nor the exact TDM specifications I can only guess a solution (which might break the library)...

**Comment by mario-fink** [comment]
The question is whether or not the TDM standard allows for _multiple_ value-ids associated to a single local_column. I assume the answer is _no_, since I don't see any reasonable thought behind this kind of construct and the only documentation I have access to states the following:  `Jede LocalColumn referenziert den zugehörigen Kanal (<measurement_quantity>#xpointer(id("usi3"))</measurement_quantity>), die zugehörige Submatrix (<submatrix>#xpointer(id("usi7"))</submatrix>) und die zugehörige ValueSequence (<values>#pointer(id("usi11"))</values>) über die eindeutige ID.` 

Therefore, the recently published version 1.0.4 allows for localcolumns missing any value-ids. The affected channels will simply be empty in the output. Please test it and let me know if it actually resolves the issue...

**Comment by adamjnicholls** [comment]
Hi @mario-fink, thanks a lot - that appears to have solved the issue for a number of my tdm files.
I'll raise another error for a different RuntimeError I'm now getting!
